pub mod es1;
pub mod es10;
pub mod es11;
pub mod es2;
pub mod es3;
pub mod es4;
pub mod es5;
pub mod es6;
pub mod es7;
pub mod es8;
pub mod es9;

fn main() {
    println!("\n********** *********** **********");
    println!("           EXERCISE 1           ");
    println!("********** *********** **********\n");
    es1::es1();
    println!("\n********** *********** **********");
    println!("           EXERCISE 2           ");
    println!("********** *********** **********\n");
    es2::es2();
    println!("\n********** *********** **********");
    println!("           EXERCISE 3           ");
    println!("********** *********** **********\n");
    es3::es3();
    println!("\n********** *********** **********");
    println!("           EXERCISE 4           ");
    println!("********** *********** **********\n");
    es4::es4();
    println!("\n********** *********** **********");
    println!("           EXERCISE 5           ");
    println!("********** *********** **********\n");
    es5::es5();
    println!("\n********** *********** **********");
    println!("           EXERCISE 6           ");
    println!("********** *********** **********\n");
    es6::es6();
    println!("\n********** *********** **********");
    println!("           EXERCISE 7           ");
    println!("********** *********** **********\n");
    es7::es7();
    println!("\n********** *********** **********");
    println!("           EXERCISE 8           ");
    println!("********** *********** **********\n");
    es8::es8();
    println!("\n********** *********** **********");
    println!("           EXERCISE 9           ");
    println!("********** *********** **********\n");
    es9::es9();
    println!("\n********** *********** **********");
    println!("           EXERCISE 10           ");
    println!("********** *********** **********\n");
    es10::es10();
    println!("\n********** *********** **********");
    println!("           EXERCISE 11           ");
    println!("********** *********** **********\n");
    es11::es11();
}
